/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSkeletonItem: typeof import('element-plus/es')['ElSkeletonItem']
    ElTable: typeof import('element-plus/es')['ElTable']
    'ElTable-': typeof import('element-plus/es')['ElTable-']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTableV2: typeof import('element-plus/es')['ElTableV2']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    QiNiuAvatar: typeof import('./src/components/commonComponents/QiNiuAvatar.vue')['default']
    QiNiuFooter: typeof import('./src/components/commonComponents/QiNiuFooter.vue')['default']
    QiniuHeader: typeof import('./src/components/commonConponents/qiniu-header.vue')['default']
    QiNiuHeader: typeof import('./src/components/commonComponents/QiNiuHeader.vue')['default']
    QiNiuLogin: typeof import('./src/components/login/QiNiuLogin.vue')['default']
    QiNiuSearch: typeof import('./src/components/commonComponents/QiNiuSearch.vue')['default']
    QiNiuVideoItem: typeof import('./src/components/commonComponents/QiNiuVideoItem.vue')['default']
    QINiuVideoSkeleton: typeof import('./src/components/commonComponents/QINiuVideoSkeleton.vue')['default']
    QINiuVideoSkletion: typeof import('./src/components/commonComponents/QINiuVideoSkletion.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
