/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTag: typeof import('element-plus/es')['ElTag']
    QiNiuAvatar: typeof import('./src/components/commonComponents/QiNiuAvatar.vue')['default']
    QiNiuFooter: typeof import('./src/components/commonComponents/QiNiuFooter.vue')['default']
    QiNiuHeader: typeof import('./src/components/commonComponents/QiNiuHeader.vue')['default']
    QiNiuLogin: typeof import('./src/components/login/QiNiuLogin.vue')['default']
    QiNiuSearch: typeof import('./src/components/commonComponents/QiNiuSearch.vue')['default']
    QiNiuVideoItem: typeof import('./src/components/commonComponents/QiNiuVideoItem.vue')['default']
    QINiuVideoSkeleton: typeof import('./src/components/commonComponents/QINiuVideoSkeleton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
