/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    QiNiuAvatar: typeof import('./src/components/commonComponents/QiNiuAvatar.vue')['default']
    QiNiuFooter: typeof import('./src/components/commonComponents/QiNiuFooter.vue')['default']
    QiniuHeader: typeof import('./src/components/commonConponents/qiniu-header.vue')['default']
    QiNiuHeader: typeof import('./src/components/commonComponents/QiNiuHeader.vue')['default']
    QiNiuSearch: typeof import('./src/components/commonComponents/QiNiuSearch.vue')['default']
    QiNiuVideoItem: typeof import('./src/components/commonComponents/QiNiuVideoItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
